### ISSUE TITLE
Buffered keyboard inputs are continue to be dispatched to newly started application in X

### ISSUE THREAD

**Issue by EricPell** [microsoft/wslg#207]
# Environment

```none
Windows build number: 21382
Your Distribution version: Ubuntu 20.04, 20.10 and 21.04
Your WSLg version: 1.0.19
```

# Steps to reproduce

Open emacs from a terminal, such as Windows Terminal

Use ctrl-x ctrl-c to close emacs

Reopen the terminal, and click the text-entry butter and "c" will repeat over and over until you press "ctrl-c"

This will persist upon reopening, until: You press "ctrl-c again" or  
you restart WSL with `wsl --shutdown`

#  Expected behavior

I expect "ctrl-x ctrl-c" to gracefully exit the program, without resulting in something being hung, which waits for the next ctrl-c to stop the key entry.

# Actual behavior

See attached screenshot

![image](https://user-images.githubusercontent.com/23527825/118500100-cc0ddc00-b727-11eb-905b-20b669839179.png)

**Comment by chrisblanton** [comment]
I am also experiencing this issue.  
Here is my `uname -a` 
Linux chrishome 5.10.16.3-microsoft-standard-WSL2 #1 SMP Fri Apr 2 22:23:49 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
My Windows 10 is Build 21382.co_release.210511-1415. WSL version 1.0.19

**Comment by hideyukn88** [comment]
Hi, thanks for reporting issue! I would like to clarify the reproduce step,

1: Use ctrl-x ctrl-c to close emacs **(not terminal)** ?
2: Reopen the emacs **(not terminal?)**, and click the text-entry butter and "c" will repeat over and over until you press "ctrl-c"

Thus basically I tried launching and closing emacs twice in row, but I do not encounter this issue. Am I missing something ?thanks!

**Comment by EricPell** [comment]
> 1: Use ctrl-x ctrl-c to close emacs **(not terminal)** ?

Yes. I am not aware of a default key-binding to close a terminal that uses 'ctrl-x ctrl-c'.

> 2: Reopen the emacs **(not terminal?)**, and click the text-entry butter and "c" will repeat over and over until you press "ctrl-c"

Yes, emacs.
 
> Thus basically I tried launching and closing emacs twice in row, but I do not encounter this issue. Am I missing something ?thanks!

You can avoid it with carefully placed mouse clicking.  I don't know exactly what you are doing, so it's hard to say.

**Comment by chrisblanton** [comment]
@hideyukn88 For your question 1, that is the default for closing emacs, not the terminal. 
Try this:
1. Open the emacs GUI via emacs. 
2. Close emacs by Ctrl-x ctrl-c 
3. Reopen emacs GUI and click in the GUI. 

I just did this and got the offending behavior just now.

**Comment by EricPell** [comment]
@hideyukn88  I didn't realize what you may have suggested until @chrisblanton  made his comment. Using "ctrl-c" to terminate a program on the command line of a terminal would kill emacs.

Ctrl-x Ctrl-c is how you exit emacs, gracefully. Ctrl-C passes SIGINT, which will interrupt and kill emacs, in this case. That is not what we are talking about.

**Comment by hideyukn88** [comment]
Thanks, so this is what I did.

1: from gnome-terminal, 'emacs -nw' - this opens emacs inside gnome-terminal.
2: 'M-&' and type 'emacs &' - this opens emacs GUI. Is this what you mean by "Open the emacs GUI via emacs." ?
3: 'C-x' 'C-c' on emacs on gnome-terminal.
4: it asks "active process exist", answer 'yes'.
5: then both emacs (on gnome-terminal) and emacs GUI terminated.
6: So how do I open emacs GUI ? I typed 'emacs &' on gnome-terminal, it looks come up fine and no repeated 'c' issue observed.

I guess I'm still missing something...

Thanks!

**Comment by EricPell** [comment]
@hideyukn88 That is not reproducing the steps. In no where is it being said to open a window less instance of emacs inside a terminal, and the launch another instance of emacs from inside of that. 

Perhaps it would be best to keep the thread clear for people discussing this issue?

**Comment by hideyukn88** [comment]
@EricPell , I would like to understand the more precise repro step (such as exact command/key input), if you can provide that, very appreciated, thanks!

**Comment by EricPell** [comment]
I made a  typo in the original post that has been fixed that said "close the terminal with ctrl-x ctr-c"

That is the key binding to close emacs. I assume you are familiar with emacs?

**Comment by EricPell** [comment]
@hideyukn88 I was able to capture a screen shot that will help. The input that is being repeated is ctrl-c. It happened when I did NOT click on the emacs window. I left the screenshot below. It should help that emacs recorded what happened automatically.

![image](https://user-images.githubusercontent.com/23527825/118532527-59145d80-b747-11eb-8a13-9f06d4b48508.png)

**Comment by hideyukn88** [comment]
@EricPell , would you please check weston.log at /mnt/wslg and if the log has below message when this occurred ? thanks!

Key repeat discarded, Wayland compositor doesn't seem to be processing events fast enough!

**Comment by EricPell** [comment]
@hideyukn88 No, that is not there. But there are thousands of repeats of the following:

[20:41:58.653] shell_blend_overlay_icon: app 48x48; overlay 128x128; scale 4.67x4.67
[20:41:58.653] rdp_rail_set_window_icon: original icon width:48 height:48 format:537036936
[20:41:58.653] rdp_rail_set_window_icon: converted icon width:48 height:48 format:537036936
[20:41:58.726] Client: ClientGetAppidReq: pid:8690 appId:Emacs
[20:41:58.727] shell_blend_overlay_icon: app 48x48; overlay 128x128; scale 4.67x4.67
[20:41:58.727] rdp_rail_set_window_icon: original icon width:48 height:48 format:537036936
[20:41:58.727] rdp_rail_set_window_icon: converted icon width:48 height:48 format:537036936
[20:43:07.572] Client: clipboard_client_format_list clipboard format list: numFormats:4
[20:43:07.572] Client: clipboard_client_format_list clipboard formats[0]: formatId:13, formatName:CF_UNICODETEXT
[20:43:07.572] Client: clipboard_client_format_list clipboard formats[1]: formatId:16, formatName:CF_LOCALE
[20:43:07.572] Client: clipboard_client_format_list clipboard formats[2]: formatId:1, formatName:CF_TEXT
[20:43:07.572] Client: clipboard_client_format_list clipboard formats[3]: formatId:7, formatName:CF_OEMTEX
[20:43:07.572] Client: clipboard_client_format_list (0x7f77cc000c60) allocated
[20:43:07.572] Client: clipboard_client_format_list (0x7f77cc000c60) mine_type:"text/plain;charset=utf-8"
[20:43:07.572] RDP clipboard_data_source_publish (0x7f77cc000c60)
[20:43:07.572] RDP clipboard_data_source_cancel (0x7f77cc000de0)
[20:43:07.572] RDP clipboard_data_source_send (0x7f77cc000c60) fd:97, mime-type:"text/plain;charset=utf-8"
[20:43:07.572] RDP clipboard_data_source_send (0x7f77cc000c60) request index:0 formatId:1 CF_TEXT
[20:43:07.572] RDP clipboard_set_selection (base:0x7f77cc000c60}
[20:43:07.572] RDP clipboard_data_source_unref (0x7f77cc000de0): refcount:0
[20:43:07.575] Client: clipboard_client_format_data_response (0x7f77cc000c60) flags:2, dataLen:0
[20:43:07.575] RDP clipboard_data_source_unref (0x7f77cc000c60): refcount:1
[20:43:07.623] Client: clipboard_client_format_list clipboard format list: numFormats:4
[20:43:07.623] Client: clipboard_client_format_list clipboard formats[0]: formatId:13, formatName:CF_UNICODETEXT
[20:43:07.623] Client: clipboard_client_format_list clipboard formats[1]: formatId:16, formatName:CF_LOCALE
[20:43:07.623] Client: clipboard_client_format_list clipboard formats[2]: formatId:1, formatName:CF_TEXT
[20:43:07.623] Client: clipboard_client_format_list clipboard formats[3]: formatId:7, formatName:CF_OEMTEX
[20:43:07.623] Client: clipboard_client_format_list (0x7f77cc000de0) allocated
[20:43:07.623] Client: clipboard_client_format_list (0x7f77cc000de0) mine_type:"text/plain;charset=utf-8"
[20:43:07.623] RDP clipboard_data_source_publish (0x7f77cc000de0)
[20:43:07.623] RDP clipboard_data_source_cancel (0x7f77cc000c60)
[20:43:07.624] RDP clipboard_data_source_send (0x7f77cc000de0) fd:97, mime-type:"text/plain;charset=utf-8"
[20:43:07.624] RDP clipboard_data_source_send (0x7f77cc000de0) request index:0 formatId:1 CF_TEXT
[20:43:07.624] RDP clipboard_set_selection (base:0x7f77cc000de0}
[20:43:07.624] RDP clipboard_data_source_unref (0x7f77cc000c60): refcount:0
[20:43:07.651] Client: clipboard_client_format_data_response (0x7f77cc000de0) flags:1, dataLen:2385
[20:43:07.652] RDP clipboard_data_source_write (0x7f77cc000de0) write completed (2384 bytes)
[20:43:07.652] RDP clipboard_data_source_unref (0x7f77cc000de0): refcount:1

**Comment by hideyukn88** [comment]
@EricPell , thanks for checking, I realized that the message I pointed is from X server, so it's not captured in weston.log, sorry for confusion. now I am able to reproduce the issue, it looks the key inputs are buffered, and remains even after application is terminated, then flushed once application is relaunched. And it looks the buffering is done either at X server or weston compositor, but not at RDP backend nor Windows side. Further investigation is required, thanks for report and helping for reproduce step!

**Comment by EricPell** [comment]
@hideyukn88 Thank you for looking into this. We all appreciate how fast you all respond to issues.

And I'm sorry I was confused and perhaps impolite earlier. I didn't mean to be.

**Comment by hideyukn88** [comment]
To follow up, this issue can be reproduced with any kind of X app, such as gvim, kate, firefox, simply terminating app using "x" in titlebar while keeping input by pressing keyboard, and relaunch any X app takes input, then the buffered key inputs are dispatch to newly launched application. This does not occur with Wayland native application.

**Comment by spronovo** [comment]
Thanks for the report. Closing as a duplicate of #58 that we are using to track this issue.

**Comment by hideyukn88** [comment]
I have a fix for this, but I'm not really 100% sure if the fix also covers https://github.com/microsoft/wslg/issues/58, this reopen this issue and apply the fix for this first.

**Comment by onomatopellan** [comment]
@hideyukn88 I just tried latest weston changes but doesn't look like the issue is fixed yet. The easiest way to test it is running `glxgears` and close it with 'Esc' key. After that running `glxgears` again it will close itself because it remembers the pressed 'Esc' key.

```
$ cat /mnt/wslg/versions.txt
WSLg ( x86_64 ): <current>
Mariner: VERSION="1.0.20210224"
FreeRDP: b05321cd4e6a862aef76163a69db4e1910245736
weston: 25a4a9ec1c005d8e0bf391743f5349b9be6f3292
pulseaudio: 2f0f0b8c3872780f15e275fc12899f4564f01bd5
mesa: 2ad0684038f5732f7e4bd1a391ec9d833685fb48
```

**Comment by hideyukn88** [comment]
@onomatopellan, thanks for trying out the change, yes, I did realize that doesn't work most of times, and I have another fix validating, and it should be pushed prior to next release, thanks!

**Comment by aperomsik** [comment]
I still have this issue with emacs on wslg on released Windows 11. Is the fix included in that build?

Windows build number: 22000.194
Distribution version: Ubuntu 21.04
WSLg version: 1.0.26

**Comment by md81544** [comment]
While that has stopped the "d" characters from spewing if I quit xterm using Ctrl-D, it seems to have the status of the ctrl key stuck down. For instance if I open xterm, then close it with Ctrl-D, then open a new one, and press just "r", I get the "(reverse-i-search)" prompt (as if I'd typed Ctrl-R.

Pressing Ctrl seems to clear the status.

**Comment by iotku** [comment]
Same issue here, using the kitty terminal thru WSLg spams the last characters from when the window was last closed. For example closing the terminal with ctrl+d will result in the terminal being closed on the next launch and then spam d on the launch after that and if you exit the terminal with `exit`<CR> the enter key will repeat continuously on the next launch.

**Comment by hideyukn88** [comment]
@iotku, that spamming 'd' should be fixed at v1.0.28, please refer https://github.com/microsoft/wslg/issues/207#issuecomment-938534366, although we are aware of any modifier key issue is not fixed as I mentioned at https://github.com/microsoft/wslg/issues/207#issuecomment-938757008, please check, thanks!

**Comment by iotku** [comment]
> @iotku, that spamming 'd' should be fixed at v1.0.28, please refer [#207 (comment)](https://github.com/microsoft/wslg/issues/207#issuecomment-938534366), although we are aware of any modifier key issue is not fixed as I mentioned at [#207 (comment)](https://github.com/microsoft/wslg/issues/207#issuecomment-938757008), please check, thanks!

Ah thanks, slightly better but yes the ctrl modifier remains pressed when relaunching. In case it's of useful note I'm launching thru a taskbar shortcut which targets `C:\Windows\System32\wslg.exe ~ -d Ubuntu kitty`

**Comment by damonlynch** [comment]
It seems using a hot key of any kind to close an app triggers the problem.

I made a YouTube video to illustrate the bug: https://youtu.be/MflcrMMlNnc

In this case, using the Ctrl-Q key to exit a Qt application triggers the bug. 

Since making the video, I have come to realize that hitting enter in a default form field inside a trivial [dialog window](https://doc.qt.io/qt-5/qdialog.html) app also triggers the bug. The enter key closes the app. Enter is then continually pressed forever in apps with input after until wsl is shutdown.

**Comment by garyo** [comment]
A good simple test case is "xev" which prints all X11 events in its window. Just start it up, and it'll print keyboard events continuously. Normal behavior is it should print nothing until mouse enters/leaves, or you type in its window.

**Comment by spronovo** [comment]
Could you give a try to the updated version of WSLg shipping with the new WSL package in the Windows Store. It contains the fix to properly reset the keyboard state which should eliminate those key repeats. There remains a known issue with crtl/shift/alt key where they might end up in the wrong state and where you have to hit it again to get it reset to the right state. This is understood and an issue in msrdc, but we don't yet have a fix.

You can try the latest version of WSL in the store by following this [link](https://aka.ms/wslstorepage). 

And for more info take a peek at our [blog](https://devblogs.microsoft.com/commandline/a-preview-of-wsl-in-the-microsoft-store-is-now-available/) on this.

**Comment by garyo** [comment]
I first installed the latest WSLg from https://github.com/microsoft/wslg/releases/download/v1.0.28/wsl_graphics_support_x64.msi, and that did not fix it for me. But your WSL preview link does fix the main issue, and I confirm the CTRL issue is still present. I will continue to use the emacs workaround from @avasopht -- thanks for that!

**Comment by damonlynch** [comment]
>  
> Could you give a try to the updated version of WSLg shipping with the new WSL package in the Windows Store. It contains the fix to properly reset the keyboard state which should eliminate those key repeats. 

It now works for me on my test program. Plus, the update experience to the new WSL package from the Windows Store has been seamless thus far. Thank you.

**Comment by hideyukn88** [comment]
This issue is kept opened to track "stuck modifier key issue" discussed at https://github.com/microsoft/wslg/issues/207#issuecomment-938757008,

**Comment by hideyukn88** [comment]
This issue is kept opened to track "stuck modifier key issue" discussed at https://github.com/microsoft/wslg/issues/207#issuecomment-938757008 until the fix, which will be made in Windows RDP client software, msrdc.exe bundled in Store version of WSL, to be released.

**Comment by Re4zOon** [comment]
@hideyukn88 Hi,

Is there a github (or anywhere else) an issue for the RDP client software?
If so, can you please drop it here, so we can track it more easily? :)

Thank you!

**Comment by Re4zOon** [comment]
Hi,

Is there any ETA for the fix?
Still waiting to switch to WSL2.0 because of this :/

Thnak you!

**Comment by hideyukn88** [comment]
@Re4zOon, internally the fix is already integrated to WSLg, so the next release of WSLg will have the fix, thanks!

**Comment by FilkerZero** [comment]
> @Re4zOon, internally the fix is already integrated to WSLg, so the next release of WSLg will have the fix, thanks!

Any idea of when WSLg  next be released?  My Windows11 PC has a last-modified date of June 5, 2021 7:06 AM, file version 10.0.22000.1:
<img width="268" alt="image" src="https://user-images.githubusercontent.com/42746731/159174633-e4c517c4-99ba-4746-8727-92390525dcdc.png">
(C:\Windows\System32\wslg.exe)

Is there a way to get the update manually sooner than general release?

**Comment by FilkerZero** [comment]
@hideyukn88 Thank you very much; I followed your directions, and it worked.  Seems my WSL2 was out of data ("`wsl --version`" was not recognized). I haven't seen the keyboard buffer problem getting the updates.
