### ISSUE TITLE
Microsoft Edge freezes when resizing window

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/wslg#272]
# Environment

```none
Windows build number: 10.0.21390.0
Your Distribution version: 20.04
Your WSLg version: Windows Subsystem for Linux WSLg Preview 1.0.22
mesa: 21.1.2~kisak1~f
```

# Steps to reproduce

Make sure Edge has hardware acceleration:

![image](https://user-images.githubusercontent.com/22350/121073841-e9165780-c787-11eb-800b-c272cbdadfab.png)

Then:

1. Open `microsoft-edge`
2. Resize the window

🐛 The window contents get frozen forever. Edge continues running since moving the mouse around still makes the mouse cursor switch to the respective CSS rules, the view never rerenders again. No interesting output comes from the terminal.

- This reproduces with any other Chromium-based apps: VS Code, Google Chrome
- I've found a workaround: `--disable-gpu`

Here's how it looks:

![recording (13)](https://user-images.githubusercontent.com/22350/121074304-87a2b880-c788-11eb-94c8-cd9237f722d5.gif)

### /mnt/wslg/weston.log

Nothing interesting here...

```
[20:59:04.664] set_position_from_xwayland: XWM 940, 316; geometry 32, 32; view 908, 284
[20:59:04.737] Client: ClientGetAppidReq: pid:5369 appId:Microsoft-edge-dev
```

### /mnt/wslg/versions.txt

```
$ cat 
WSLg ( x86_64 ): 1.0.22+Branch.main.Sha.d7102a7ff8a3bb04bbcd3483c3f7d7a7633686a1
Mariner: VERSION="1.0.20210224"
FreeRDP: 5f083fa0b97d433d6204985f6047886e29c1c61e
weston: 9e402088aa2cd9316851ea20b9befbcf3b9c9564
pulseaudio: 2f0f0b8c3872780f15e275fc12899f4564f01bd5
mesa:
```

### `glxinfo -B`

```
name of display: :0
NVD3D10: CPU cyclestats are disabled on client virtualization
NVD3D10: CPU cyclestats are disabled on client virtualization
display: :0  screen: 0
direct rendering: Yes
Extended renderer info (GLX_MESA_query_renderer):
    Vendor: Microsoft Corporation (0xffffffff)
    Device: D3D12 (NVIDIA GeForce GTX 1050 Ti) (0xffffffff)
    Version: 21.1.2
    Accelerated: yes
    Video memory: 20361MB
    Unified memory: no
    Preferred profile: core (0x1)
    Max core profile version: 3.3
    Max compat profile version: 3.1
    Max GLES1 profile version: 1.1
    Max GLES[23] profile version: 3.0
OpenGL vendor string: Microsoft Corporation
OpenGL renderer string: D3D12 (NVIDIA GeForce GTX 1050 Ti)
OpenGL core profile version string: 3.3 (Core Profile) Mesa 21.1.2 - kisak-mesa PPA
OpenGL core profile shading language version string: 3.30
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile

OpenGL version string: 3.1 Mesa 21.1.2 - kisak-mesa PPA
OpenGL shading language version string: 1.40
OpenGL context flags: (none)

OpenGL ES profile version string: OpenGL ES 3.0 Mesa 21.1.2 - kisak-mesa PPA
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.00
```

### `microsoft-edge`

```
[7386:7420:0607/210351.107311:ERROR:bus.cc(393)] Failed to connect to the bus: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory
[7386:7544:0607/210351.181791:ERROR:bus.cc(393)] Failed to connect to the bus: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory
[7386:7544:0607/210351.181846:ERROR:bus.cc(393)] Failed to connect to the bus: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory
[7386:7544:0607/210351.181872:ERROR:bus.cc(393)] Failed to connect to the bus: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory
[7386:7544:0607/210351.181891:ERROR:bus.cc(393)] Failed to connect to the bus: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory
[7386:7544:0607/210351.181910:ERROR:bus.cc(393)] Failed to connect to the bus: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory
[7476:7476:0607/210352.374334:ERROR:sandbox_linux.cc(374)] InitializeSandbox() called with multiple threads in process gpu-process.
[7386:7386:0607/210352.564764:ERROR:CONSOLE(1)] "PSL: window.chrome.ntpSettingsPrivate.getPref does not have campaigns. [object Object] Mon Jun 07 2021 21:03:52 GMT+0200 (Central European Summer Time)", source: https://assets.msn.com/bundles/v1/edgeChromium/latest/vendors.75f4411cef43db1eb41a.js (1)
[7386:7386:0607/210353.912187:ERROR:CONSOLE(1)] "Request has failed. [object Object] Mon Jun 07 2021 21:03:53 GMT+0200 (Central European Summer Time)", source: https://assets.msn.com/bundles/v1/edgeChromium/latest/vendors.75f4411cef43db1eb41a.js (1)
[7386:7386:0607/210353.912347:ERROR:CONSOLE(1)] " [object Object] Mon Jun 07 2021 21:03:53 GMT+0200 (Central European Summer Time)", source: https://assets.msn.com/bundles/v1/edgeChromium/latest/vendors.75f4411cef43db1eb41a.js (1)
[7386:7386:0607/210402.033331:ERROR:CONSOLE(1569)] "Mon Jun 07 2021 21:04:02 GMT+0200 (Central European Summer Time): 1623092642031 {"id":20155,"source":"SAMAdService.ts","severity":0,"pb":{"build":"20210604.540","appType":"edgeChromium","pcsVersion":"20210528.7_master","buildAlias":"latest","customMessage":"pageType: edgechrntp, status: 0, StatusText: "},"message":"Error calling SAMRTB Ajax"}", source: https://assets.msn.com/bundles/v1/edgeChromium/latest/common.7c77a7611a32c8a0632a.js (1569)
[7386:7386:0607/210402.169025:ERROR:CONSOLE(1569)] "Mon Jun 07 2021 21:04:02 GMT+0200 (Central European Summer Time): 1623092642168 {"id":20155,"source":"SAMAdService.ts","severity":0,"pb":{"build":"20210604.540","appType":"edgeChromium","pcsVersion":"20210528.7_master","buildAlias":"latest","customMessage":"pageType: edgechrntp, status: 0, StatusText: "},"message":"Error calling SAMRTB Ajax"}", source: https://assets.msn.com/bundles/v1/edgeChromium/latest/common.7c77a7611a32c8a0632a.js (1569)
[7386:7386:0607/210402.565638:ERROR:CONSOLE(1569)] "Mon Jun 07 2021 21:04:02 GMT+0200 (Central European Summer Time): 1623092642565 {"id":20155,"source":"SAMAdService.ts","severity":0,"pb":{"build":"20210604.540","appType":"edgeChromium","pcsVersion":"20210528.7_master","buildAlias":"latest","customMessage":"pageType: edgechrntp, status: 0, StatusText: "},"message":"Error calling SAMRTB Ajax"}", source: https://assets.msn.com/bundles/v1/edgeChromium/latest/common.7c77a7611a32c8a0632a.js (1569)
```

#  Expected behavior

I expected the app not to freeze at all.

# Actual behavior

The app freezes when resizing the window.

**Comment by jenatali** [comment]
I can reproduce this, but it's not 100% repro. Occasionally I can successfully resize using the window edges, and I have no problem using maximize/restore.

**Comment by hideyukn88** [comment]
@joaomoreno, would you please check what GPU driver version does your system has in Windows side ? You can run dxdiag to check GPU driver version on Windows. Could it be recently released NVIDIA 470.76 ? thanks!

**Comment by onomatopellan** [comment]
What happens if you run Edge with gpu but using wayland instead of x11?
`microsoft-edge --enable-features=UseOzonePlatform --ozone-platform=wayland`

**Comment by joaomoreno** [comment]
That does work. But some other features don't work:

- Can't scroll
- Can't paste contents after closing the app

---

## No flags

```
Canvas: Hardware accelerated
Compositing: Hardware accelerated
Multiple Raster Threads: Enabled
Out-of-process Rasterization: Disabled
OpenGL: Enabled
Rasterization: Software only. Hardware acceleration disabled
Skia Renderer: Enabled
Video Decode: Software only. Hardware acceleration disabled
Vulkan: Disabled
WebGL: Hardware accelerated
WebGL2: Hardware accelerated
```

## `--disable-gpu`

```
Canvas: Software only, hardware acceleration unavailable
Compositing: Software only. Hardware acceleration disabled
Multiple Raster Threads: Enabled
Out-of-process Rasterization: Disabled
OpenGL: Disabled
Rasterization: Software only. Hardware acceleration disabled
Skia Renderer: Enabled
Video Decode: Software only. Hardware acceleration disabled
Vulkan: Disabled
WebGL: Software only, hardware acceleration unavailable
WebGL2: Software only, hardware acceleration unavailable
```

## `--enable-features=UseOzonePlatform --ozone-platform=wayland`

```
Canvas: Hardware accelerated
Compositing: Software only. Hardware acceleration disabled
Multiple Raster Threads: Enabled
Out-of-process Rasterization: Disabled
OpenGL: Enabled
Rasterization: Software only. Hardware acceleration disabled
Skia Renderer: Enabled
Video Decode: Software only. Hardware acceleration disabled
Vulkan: Disabled
WebGL: Hardware accelerated but at reduced performance
WebGL2: Hardware accelerated but at reduced performance
```

**Comment by onomatopellan** [comment]
Installed Nvidia new official drivers 471.11 but still has this resizing issue with X11 Edge+GPU.

Wayland Edge+GPU resizing works but scroll is indeed broken since Edge-dev version 92.0.902.

So the latest Edge-dev where window resizing works for me with GPU enabled and working scroll is version 92.0.891 with wayland.
```
sudo apt install microsoft-edge-dev=92.0.891.1-1
microsoft-edge-dev --enable-features=UseOzonePlatform --ozone-platform=wayland
```

**Comment by akuropka** [comment]
Maybe the issue is kernel related.
Just happened to notice that the issue is resolved (at least at my side) while using this kernel: https://github.com/peseoane/linux-kernels-wsl2/releases/tag/5.14-rc2

**Comment by onomatopellan** [comment]
This problem seems fixed for me. I updated everything and now I can resize x11 apps with GPU acceleration without problem.

```
Windows build number: 10.0.22000.194
Your Distribution version: 20.04
WSL2 kernel: 5.10.60.1-microsoft-standard-WSL2
Your WSLg version: Windows Subsystem for Linux WSLg Preview 1.0.28
mesa: Mesa 21.3.0-devel (git-0a592db 2021-10-05 focal-oibaf-ppa)

GPU: NVIDIA GeForce GT 710
Microsoft Edge 96.0.1032.0 dev
```

**Comment by TTSKarlsson** [comment]
Windows 11 21H2 22000.194
Nvidia GameReady Driver 510.06

Problem persists when running the apps as explained https://docs.microsoft.com/en-us/windows/wsl/tutorials/gui-apps

But it is resolved after installing X11 (`sudo apt install x11-apps -y`), which is not an outspoken requirement.

**Comment by akuropka** [comment]
It works meanwhile at my end as well but I do not have x11-apps installed.
