### ISSUE TITLE
The whole PC freezes after running wsl --shutdown

### ISSUE THREAD

**Issue by skyblueplus** [microsoft/wslg#728]
# Environment

```none
Windows build number: Version 10.0.22598.200, and also in previous builds.
Your Distribution version: Tested in Ubuntu 20.04, 21.04 and 22.04.
Your WSLg version: 1.0.33
```

# Steps to reproduce

**WSL logs**: 

No errors in logs since this happens when ```wsl --shutdown``` is run and this also causes the PC to shutdown.
Using latest Nvidia drivers.
Solution seems to be that you need to ensure all gui related apps are killed before running ```wsl --shutdown``` , or run `wsl -t Ubuntu && wsl --shutdown`. But this does not always work.

* `versions.txt`
```
WSLg ( x86_64 ): 1.0.33+Branch.main.Sha.d57addbe6309d0a453123c91e6117fc21871496c
Mariner: VERSION="1.0.20220226"
FreeRDP: c574044a10003e50453acb4cf42801c5833fb572
weston: 651d33374f9b9e93e1cf1210faff13bcd339f132
pulseaudio: 2f0f0b8c3872780f15e275fc12899f4564f01bd5
```

#  Expected behavior

Successfully shutdown WSL after running ```wsl --shutdown``` .
# Actual behavior

The whole PC freezes (including mouse and all keyboard combinations) and becomes unresponsive, after running ```wsl --shutdown``` .

**Comment by brokeDude2901** [comment]
same problem (NVIDIA Drivers 511.65 - RTX A5000)

**Comment by inclu-media** [comment]
same issue:

> wsl --status
```
Default Distribution: Ubuntu
Default Version: 2
WSL version: 0.58.3.0
Kernel version: 5.10.102.1
WSLg version: 1.0.33
MSRDC version: 1.2.2924
Direct3D version: 1.601.0
Windows version: 10.0.22610.1
```
> google-chrome --enable-features=UseOzonePlatform --ozone-platform=wayland

Chrome occasionally freezes, trying to resolve by
> wsl --shutdown 

The whole system hangs and needs to be rebooted.

**Comment by hideyukn88** [comment]
@skyblueplus, thanks for reporting the issue. I was able to reproduce the issue and this is the issue in Window's side kernel mode driver issue. (for internal reference, the bug number at OS bug is 39506793), thanks!

**Comment by hideyukn88** [comment]
@skyblueplus, @brokeDude2901, @inclu-media, if any of you are on Windows insider build, the fix is released to insider last week with Windows build number 25140 (https://blogs.windows.com/windows-insider/2022/06/15/announcing-windows-11-insider-preview-build-25140/). If you have a chance to try out this build and verify this issue is fixed, please let us know, thanks!

**Comment by borismcfishtank** [comment]
Thanks @hideyukn88 I'll guess I'll have to wait till it hits the beta channel. Any idea on time frames?

**Comment by LightDestory** [comment]
I am still having the same issue with Windows 11 22622.586...

Any ETA for the release of the fix on Beta channel?

**Comment by unixdaddy** [comment]
Wlsg kills my 32gb machine. I only have to open a linux distro and the machine is dead - no response. What is wslg? A virus cannot do the damage it does. Does anyone have a fix?

**Comment by hideyukn88** [comment]
@unixdaddy, to narrow down the root cause, would you please try with Graphics driver disabled? You can disable it from Device Manager, locate GPU driver node, right click on that, then select disable, then restart WSL, thanks!

**Comment by digitalnomad91** [comment]
Same thing is happening to me. Just completely locks up, my mouse won't move can't Ctrl+alt+del, nothing. Just have to physical hold the power button and restart.

**Comment by hideyukn88** [comment]
@digitalnomad91, do you see the issue just by starting up Linux distro, or by `wsl --shutdown`? And does disabling graphics driver help? thanks!

**Comment by LightDestory** [comment]
I saw some activity so I want to add my experience.

I have a laptop running Windows 11 insider preview on beta channel with the following specs (I will loat generic info):
- Intel 10th i7
- 32gb ram
- rtx 2070 super
The laptop is mux-less, so I don't have a direct option to decide which gpu to use.

I started wsl by opening my Ubuntu distro, I executed a normal apt upgrade and then I tried executing wsl shutdown which frozen my laptop


At that time the gpu led was red, so nvidia gpu was running something. I can't guarantee that the process using nvidia gpu was wsl at that time.


I can say that the freeze doesn't happen everything, today I executed a wsl shutdown without freezing

**Comment by hideyukn88** [comment]
The fix for system freezes by `wsl --shutdown` is released in KB5017389, which is currently in release preview state. Anyone on Windows insider channel should be able to install, thus if you happen to install it, please let us know how it goes, thanks!

**Comment by digitalnomad91** [comment]
> @digitalnomad91, do you see the issue just by starting up Linux distro, or by `wsl --shutdown`? And does disabling graphics driver help? thanks!

The issue is when I run the shutdown command.  I have my monitors plugged in to my 3070 ti so I'm not sure how to disable the graphics drivers, do I need to plug in to the onboard Intel graphics? I don't use any wsl GUI stuff btw, I just run a lot of dev environments and connect to it with windows terminal & vscode. 

Also idk if it's relevant, but I am running the genie systemd hack. I was about to update wsl and remove it and try installing the new Microsoft native systemd implementation when it happened again.

**Comment by LightDestory** [comment]
> The fix for system freezes by `wsl --shutdown` is released in KB5017389, https://blogs.windows.com/windows-insider/2022/09/22/releasing-windows-11-build-22621-607-to-the-release-preview-channel/, which is currently in release preview state. Anyone on Windows insider channel should be able to install, thus if you happen to install it, please let us know how it goes, thanks!

Is this fix included on 22623.670 as well?

I am currently on 22622 and I didn't get 22621.607

**Comment by hideyukn88** [comment]
@LightDestory,

>> Is this fix included on 22623.670 as well?

Yes, it is.

**Comment by hideyukn88** [comment]
@digitalnomad91 

>> I'm not sure how to disable the graphics drivers, do I need to plug in to the onboard Intel graphics?

You can temporarily disable the graphics driver from Device Manager.

![image](https://user-images.githubusercontent.com/13857962/193137896-0754053d-0e0c-4b65-a19c-76863e7fc872.png)

**Comment by brunohubner** [comment]
@hideyukn88 Isn't there another way to solve this problem without joining the Windows Insider program?

In your suggestion I should disable my RTX 2060 for a few moments to be able to run the `wsl --shutdown` ?

**Comment by hideyukn88** [comment]
@brunohubner, if everything goes as planned, it will be released to non-insider channel by late November, thanks!

**Comment by ctsyeh** [comment]
Just got a new laptop and I am running into this issue.  Capturing my configuration and observation below.

19:58:49.27 => wsl --update
Checking for updates...
No updates are available.
Kernel version: 5.10.102.1

19:59:01.07 => ver
Microsoft Windows [Version 10.0.19044.2251]

Running with Xpra Server, not WSLg

Xpra Server          Nvidia Driver          Wsl --shutdown
Running               Enabled                  Freeze
Running               Disabled                 Shutdown successfully
Terminated          Enabled                   Shutdown successfully
Terminated          Disable                    Did not test

**Comment by schwaerz** [comment]
Same happens with Windows 10 21H2 + KB5020030 + NVIDIA graphics. Supposedly it would happen for the other Win10 wslg updates, too.
Any updates planned for the Win10 wslg support?

**Comment by jssblck** [comment]
Same happening to me, also nvidia graphics. I mostly use WSL through a remote SSH connection, and this manifests as "the SSH session suddenly dies, then I have to go hold the power button to turn the PC off".

```
WSL version: 1.0.3.0
Kernel version: 5.15.79.1
WSLg version: 1.0.47
MSRDC version: 1.2.3575
Direct3D version: 1.606.4
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.22621.1105
```

**Comment by s4m0r4m4** [comment]
I am also consistently seeing my computer freeze when I run `wsl --shutdown`. Here is my version info

```
WSL version: 1.2.5.0
Kernel version: 5.15.90.1
WSLg version: 1.0.51
MSRDC version: 1.2.3770
Direct3D version: 1.608.2-61064218
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.19045.3208
```
