### ISSUE TITLE
High CPU load (Virtual Machine Worker Process + System) when session is IDLE

### ISSUE THREAD

**Issue by Gerdya** [microsoft/wslg#819]
### Version

Win: 10.0.22622.575  WSL: 0.66.2.0 Kernel: 5.15.57.1

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.15.57.1

### Distro Version

Ubuntu 22.04

### Repro Steps

Install WSL2/Ubuntu and start a session. Obeserve in Windows Task manager high load on both "Virtual Machine Worker Process" and "System". Both taking 15% CPU each for a combined 30+% CPU load. After wsl --shutdown the issue is gone.

### Expected Behavior

No significant CPU usage when Linux/WSL is IDLE.

### Actual Behavior

This is on my Surface Pro X (aarch64) - other ARM machine users for instance with the new Thinkpad X13S have reported similar obervations.

Both "Virtual Machine Worker Process" and "System". Each taking  roughly 15% CPU for a combined 30% CPU load. 

Linux System is idle:

wsl --system -d Ubuntu Top

  PID USER      PR  NI    VIRT    RES  %CPU  %MEM     TIME+ S COMMAND
    1 root      20   0    2.1m   1.5m   0.0   0.0   0:00.02 S /init
    2 root      20   0    2.2m   1.6m   0.0   0.0   0:00.01 S  `- /init
   27 root      20   0    2.3m   0.1m   0.0   0.0   0:00.00 S      `- /init
   28 root      20   0    2.3m   0.1m   0.0   0.0   0:00.07 S          `- /init
   30 wslg      20   0    9.5m   4.4m   0.0   0.1   0:00.09 S              `- -bash
    7 root      20   0    2.1m   0.2m   0.0   0.0   0:00.00 S  `- /init
    8 root      20   0   45.9m   7.3m   0.0   0.1   0:00.01 S      `- /usr/bin/WSLGd
   11 wslg      20   0  674.9m  34.3m   0.0   0.4   0:00.55 S          `- /usr/bin/weston --backend=rdp-backend.so --modules=wslgd-notify.so --xwa+
   15 wslg      20   0   18.5m   7.2m   0.0   0.1   0:00.03 S              `- /usr/libexec/weston-rdprail-shell
   31 wslg      20   0   44.7m  17.7m   0.0   0.2   0:00.04 S              `- /usr/bin/Xwayland :0 -rootless -core -listen 37 -wm 38 -terminate -n+
   16 wslg      20   0    2.0m   1.5m   0.0   0.0   0:00.00 S          `- /init /mnt/c/Program Files/WindowsApps/MicrosoftCorporationII.WindowsSub+
   17 message+  20   0    7.8m   3.3m   0.0   0.0   0:00.02 S          `- /usr/bin/dbus-daemon --syslog --nofork --nopidfile --system
   18 wslg      20   0  230.1m   7.2m   0.0   0.1   0:00.06 S          `- /usr/bin/pulseaudio --log-target=file:/mnt/wslg/pulseaudio.log --load=mo+
   22 wslg      20   0    7.6m   0.3m   0.0   0.0   0:00.00 S  `- /usr/bin/dbus-daemon --syslog --fork --print-pid 6 --print-address 8 --session
   93 root      20   0    2.1m   0.1m   0.0   0.0   0:00.00 S  `- /init
   94 root      20   0    2.1m   0.1m   0.0   0.0   0:00.00 S      `- /init
   95 wslg      20   0    6.4m   2.1m   0.0   0.0   0:00.02 R          `- top

### Diagnostic Logs

[WslLogs-2022-08-24_17-14-22.zip](https://github.com/microsoft/WSL/files/9417304/WslLogs-2022-08-24_17-14-22.zip)

**Comment by MdeRhoter** [comment]
Much appreciated 👍

**Comment by Gerdya** [comment]
I assume this has not been reviewed by WSLG developers yet? Let me stress, that this is a very serious issue, which makes WSL almost un-usable on many if not most ARM devices. Issue is, that, this constant 30+% load on the system affects responsiveness, battery drain and available processing resources - you essentially have to shutdown WSL when not in use.

Let me know if you need more logs - as I initially only uploaded the WSL logs.

**Comment by puzzone** [comment]
Same here on a Windows on ARM - Qualcomm 8cx gen3 (Thinkpad X13s)

Wondered why runtime is so bad until I noticed the 30% CPU penalty.
Need to shutdown WSL if not absolutely needed.

**Comment by hideyukn88** [comment]
@puzzone, @Gerdya, to narrow down the cause, would you please disable WSL GUI support by below, and check if you observe the issue? Please set below in .wslconfig, thanks!

```
[wsl2]
guiApplications=false
```

For further details, please refer https://docs.microsoft.com/en-us/windows/wsl/wsl-config.

**Comment by dtgeorge** [comment]
> 

Issue still present!

**Comment by hideyukn88** [comment]
@dtgeorge, would you please collect WSL log by following instruction at 8) at https://github.com/Microsoft/WSL/blob/master/CONTRIBUTING.md ? thanks!

**Comment by dtgeorge** [comment]
[WslLogs-2022-09-12_23-15-31.zip](https://github.com/microsoft/wslg/files/9551569/WslLogs-2022-09-12_23-15-31.zip)

**Comment by hideyukn88** [comment]
@dtgeorge, thanks for the log. your log doesn't exhibit the issue @benhillis noted at https://github.com/microsoft/wslg/issues/819#issuecomment-122775983, so next step would be collecting more detailed log, would you please do below?

0) extract log.wprp from [log.zip](https://github.com/microsoft/wslg/files/9551876/log.zip)
1) make sure WSL is idle and CPU high load issue is happening.
2) from run admin privileged cmd.exe, run `wpr -start log.wprp!GPUView.Verbose -filemode`
3) wait 3 sec, then `wpr -stop output.etl`
4) please share output.etl with us.

Thanks!

**Comment by Gerdya** [comment]
I did upload both, logs and output.etl (output.zip)

[WslLogs-2022-09-12_23-47-21.zip](https://github.com/microsoft/wslg/files/9552058/WslLogs-2022-09-12_23-47-21.zip)
[output.zip](https://github.com/microsoft/wslg/files/9552063/output.zip)

**Comment by dtgeorge** [comment]
@hideyukn88 , does @Gerdya logs enough?

**Comment by puzzone** [comment]
Hi all, 
please find my logs with wslg dis- and enabled below. 
And big thanks for your help!

[wslg-DISABLED.zip](https://github.com/microsoft/wslg/files/9556833/wslg-DISABLED.zip)
[wslg-ENABLED.zip](https://github.com/microsoft/wslg/files/9556834/wslg-ENABLED.zip)

**Comment by hideyukn88** [comment]
> @hideyukn88 , does @Gerdya logs enough?

Yes, the output.etl is what we need, thanks!

**Comment by hideyukn88** [comment]
Now we understood the issue and the fix is being made. The fix will be at Windows OS side (not WSL/WSLg), thus ETA for fix is still unknown, once I know more, will post here, thanks!

**Comment by Gerdya** [comment]
@hideyukn88 Thanks for root-causing the issue!

**Comment by Gerdya** [comment]
Looks like it is fixed in the dev channel build 25211

[Preview Build 25211 Release Notes](https://blogs.windows.com/windows-insider/2022/09/29/announcing-windows-11-insider-preview-build-25211/)

Hopefully beta channel is next.

**Comment by leuler27** [comment]
Is there deployment ETA for the normal Win 11 build? Still an issue on Pro X.

**Comment by Gerdya** [comment]
It is been a month since the dev channel fix. Nothing on the other channels as far :(

**Comment by MdeRhoter** [comment]
Seems to have been fixed!

`Edition	Windows 11 Pro
Version	22H2
OS build	22621.900
Serial number	035099294753
Experience	Windows Feature Experience Pack 1000.22638.1000.0
`

**Comment by vanc** [comment]
Idle CPU usage was around 1%-3% with Ubuntu 22.04 running along with a bunch of other apps (Firefox, etc.). Excellent!

**Comment by Macmee** [comment]
Still experiencing this issue Edition	Windows 11 Pro
Version	22H2
Installed on	‎8/‎28/‎2022
OS build	22621.755
Experience	Windows Feature Experience Pack 1000.22636.1000.0

**Comment by Macmee** [comment]
To add, I have a Surface Pro 9 ARM variant, Virtual Machine Worker Process is using 12.5% CPU and System using 12.5% while Debian on the WSL side is fully idle.

**Comment by Macmee** [comment]
@hideyukn88 @gerdya To add, I have a Surface Pro 9 ARM variant, Virtual Machine Worker Process is using 12.5% CPU and System using 12.5% while Debian on the WSL side is fully idle.
