### ISSUE TITLE
X11 GUI does not open anymore

### ISSUE THREAD

**Issue by lohrm-stabl** [microsoft/wslg#853]
### Windows build number:

10.0.22000.0

### Your Distribution version:

22.04

### Your WSL versions:

WSL version: 0.66.2.0
Kernel version: 5.15.57.1
WSLg version: 1.0.42
MSRDC version: 1.2.3401
Direct3D version: 1.606.4
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.22000.978

### Steps to reproduce:

Not sure this is reproducible since WSL worked fine just a few days ago. I don't remember changing anything significant.
When launching any X app, the stdout looks like it works fine, but no actual window opens anymore.

Launch `xeyes`.

Nothing happens:
![image](https://user-images.githubusercontent.com/111898561/194820913-a96fc936-a140-4434-a120-70943c9384ad.png)

### WSL logs:

<details>
<summary>stderr.log</summary>

```
dbus[16]: Unknown username "systemd-oom" in message bus configuration file
dbus[16]: Unknown username "pulse" in message bus configuration file
could not load cursor 'grabbing'
could not load cursor 'dnd-move'
could not load cursor 'dnd-copy'
glamor: 'wl_drm' not supported
Missing Wayland requirements for glamor GBM backend
Failed to initialize glamor, falling back to sw
The XKEYBOARD keymap compiler (xkbcomp) reports:
> Internal error:   Could not resolve keysym XF86FullScreen
Errors from xkbcomp are not fatal to the X server
The XKEYBOARD keymap compiler (xkbcomp) reports:
> Warning:          Unsupported maximum keycode 569, clipping.
>                   X11 cannot support keycodes above 255.
> Internal error:   Could not resolve keysym XF86FullScreen
Errors from xkbcomp are not fatal to the X server
```

</details>

<details>
<summary>weston.log</summary>

```
Date: 2022-10-10 CEST
[09:50:20.215] weston 9.0.0
               https://wayland.freedesktop.org
               Bug reports to: https://gitlab.freedesktop.org/wayland/weston/issues/
               Build: 9.0.0-160-gd57e0de2
[09:50:20.215] Command line: /usr/bin/weston --backend=rdp-backend.so --modules=wslgd-notify.so --xwayland --log=/mnt/wslg/weston.log --socket=wayland-0 --shell=rdprail-shell.so --logger-scopes=log,rdp-backend,rdprail-shell
[09:50:20.215] OS: Linux, 5.15.57.1-microsoft-standard-WSL2, #1 SMP Wed Jul 27 02:20:31 UTC 2022, x86_64
[09:50:20.216] Using config file '/home/wslg/.config/weston.ini'
[09:50:20.217] Output repaint window is 7 ms maximum.
[09:50:20.217] Loading module '/usr/lib/libweston-9/rdp-backend.so'
[09:50:20.226] using FreeRDP version 2.4.0
Date: 2022-10-10 CEST
[09:50:20.226] RDP backend: WESTON_RDP_DEBUG_LEVEL: 3
[09:50:20.226] RDP backend: rdp_monitor_refresh_rate: 60000
[09:50:20.226] RDP backend: timer resolution tv_sec:0 tv_nsec:1
[09:50:20.226] RDP backend: Environment dump - start
[09:50:20.226]   WSL2_DEFAULT_APP_ICON=/usr/share/icons/wsl/linux.png
[09:50:20.226]   SHELL=/bin/bash
[09:50:20.226]   WSL2_GUI_APPS_ENABLED=1
[09:50:20.226]   WSL_DISTRO_NAME=
[09:50:20.226]   WSL2_VM_ID=EC80DE62-C469-4409-93E1-9C3F20BD56F6
[09:50:20.226]   XCURSOR_PATH=/usr/share/icons
[09:50:20.226]   XCURSOR_SIZE=16
[09:50:20.226]   NAME=LOHRM-STABL
[09:50:20.226]   PWD=/home/wslg
[09:50:20.226]   LOGNAME=wslg
[09:50:20.226]   WSL_FEATURE_FLAGS=d
[09:50:20.226]   WSL2_USER_PROFILE=C:\Users\MichaelLohr
[09:50:20.226]   WSL2_DISTRO_NAME=Ubuntu
[09:50:20.226]   _=/usr/bin/weston
[09:50:20.226]   PULSE_AUDIO_RDP_SINK=/mnt/wslg/PulseAudioRDPSink
[09:50:20.226]   HOME=/home/wslg
[09:50:20.226]   WAYLAND_DISPLAY=wayland-0
[09:50:20.226]   USE_VSOCK=3
[09:50:20.226]   WSL2_DEFAULT_APP_OVERLAY_ICON=/usr/share/icons/wsl/linux.png
[09:50:20.226]   USER=wslg
[09:50:20.226]   DISPLAY=:0
[09:50:20.226]   SHLVL=0
[09:50:20.226]   WSLGD_NOTIFY_SOCKET=/mnt/wslg/weston-notify.sock
[09:50:20.226]   XDG_RUNTIME_DIR=/mnt/wslg/runtime-dir
[09:50:20.226]   WSL2_SHARED_MEMORY_OB_DIRECTORY=WSL\EC80DE62-C469-4409-93E1-9C3F20BD56F6\wslg
[09:50:20.226]   XCURSOR_THEME=whiteglass
[09:50:20.226]   PATH=/usr/sbin:/usr/bin:/sbin:/bin:/usr/games
[09:50:20.226]   WESTON_DISABLE_ABSTRACT_FD=1
[09:50:20.226]   PULSE_AUDIO_RDP_SOURCE=/mnt/wslg/PulseAudioRDPSource
[09:50:20.226]   PULSE_SERVER=/mnt/wslg/PulseServer
[09:50:20.226]   WSL2_INSTALL_PATH=C:\Program Files\WindowsApps\MicrosoftCorporationII.WindowsSubsystemForLinux_0.66.2.0_x64__8wekyb3d8bbwe
[09:50:20.226]   WSL2_SHARED_MEMORY_MOUNT_POINT=/mnt/shared_memory
[09:50:20.226]   WESTON_CONFIG_FILE=/home/wslg/.config/weston.ini
[09:50:20.226] RDP backend: Environment dump - end
[09:50:20.226] RDP backend: FreeRDP version: 2.4.0
[09:50:20.226] Using external fd for incoming connections: 3
[09:50:20.226] Default head is being added
[09:50:20.226] Registered plugin API 'weston_rdprail_api_v1' of size 64
[09:50:20.226] RDPAPPLIST_MODULEDIR is set to /usr/lib/rdpapplist
[09:50:20.227] RDP backend: use_rdpapplist = 1
[09:50:20.242] RDP backend: use_gfxredir = 1
[09:50:20.242] RDP backend: enable_hi_dpi_support = 1
[09:50:20.242] RDP backend: enable_fractional_hi_dpi_support = 0
[09:50:20.242] RDP backend: enable_fractional_hi_dpi_roundup = 0
[09:50:20.242] RDP backend: debug_desktop_scaling_factor = 0
[09:50:20.242] RDP backend: enable_window_zorder_sync = 1
[09:50:20.242] RDP backend: enable_window_snap_arrange = 0
[09:50:20.242] RDP backend: enable_window_shadow_remoting = 1
[09:50:20.242] RDP backend: enable_display_power_by_screenupdate = 0
[09:50:20.242] RDP backend: enable_distro_name_title = 1
[09:50:20.242] RDP backend: enable_copy_warning_title = 1
[09:50:20.243] Using VSOCK for incoming connections: 3
[09:50:20.246] Registered plugin API 'weston_rdp_output_api_v1' of size 16
[09:50:20.246] Head attaching: rdp-0, index:0, is_primary: 1
[09:50:20.246] Client desktop upper left coordinate (0,0)
[09:50:20.246] disp_monitor_validate_and_compute_layout:---OUTPUT---
[09:50:20.246]  rdpMonitor[0]: x:0, y:0, width:0, height:0, is_primary:1
[09:50:20.246]  rdpMonitor[0]: weston x:0, y:0, width:0, height:0
[09:50:20.246]  rdpMonitor[0]: physicalWidth:0, physicalHeight:0, orientation:0
[09:50:20.246]  rdpMonitor[0]: desktopScaleFactor:0, deviceScaleFactor:0
[09:50:20.246]  rdpMonitor[0]: scale:1, clientScale:1.00
[09:50:20.246] Head mode change:rdp-0 NEW width:0, height:0, scale:1, clientScale:1.000000
[09:50:20.246] move head/output rdp-0 (0,0) -> (0,0)
[09:50:20.246] client origin (0,0) is (0,0) in Weston space
[09:50:20.246] Output 'rdp-0' enabled with head(s) rdp-0
[09:50:20.246] Compositor capabilities:
               arbitrary surface rotation: yes
               screen capture uses y-flip: no
               presentation clock: CLOCK_MONOTONIC_RAW, id 4
               presentation clock resolution: 0.000000001 s
[09:50:20.247] Loading module '/usr/lib/weston/rdprail-shell.so'
[09:50:20.248] RDPRAIL-shell: WESTON_RDPRAIL_SHELL_DEBUG_LEVEL: 3.
Date: 2022-10-10 CEST
[09:50:20.248] RDPRAIL-shell: allow-zap:0
[09:50:20.248] RDPRAIL-shell: binding-modifier:none
[09:50:20.248] RDPRAIL-shell: local-move:0
[09:50:20.248] RDPRAIL-shell: distro name:Ubuntu (len:6)
[09:50:20.250] RDPRAIL-shell: WSL2_DEFAULT_APP_ICON:/usr/share/icons/wsl/linux.png (loaded:yes)
[09:50:20.251] RDPRAIL-shell: WSL2_DEFAULT_APP_OVERLAY_ICON:/usr/share/icons/wsl/linux.png (loaded:yes)
[09:50:20.251] RDPRAIL-shell: WESTON_RDPRAIL_SHELL_APPEND_DISTRONAME_STARTMEN:1
[09:50:20.251] RDPRAIL-shell: WESTON_RDPRAIL_SHELL_BLEND_OVERLAY_ICON_APPLIST:1
[09:50:20.251] RDPRAIL-shell: WESTON_RDPRAIL_SHELL_BLEND_OVERLAY_ICON_TASKBAR:1
[09:50:20.251] rdp_rail_shell_initialize_notify: shell: distro name: Ubuntu
[09:50:20.252] app_list_monitor_thread: running in system-distro with user-distro: Ubuntu
[09:50:20.252] app_list_monitor_thread: open(/proc/self/ns/mnt)
[09:50:20.252] app_list_monitor_thread: open(/proc/2/ns/mnt)
[09:50:20.252] Loading module '/usr/lib/libweston-9/xwayland.so'
[09:50:20.253] app_list_monitor_thread: inotify_add_watch(/usr/share/applications)
[09:50:20.255] app_list_monitor_thread: /usr/local/share/applications doesn't exist, skipping.
[09:50:20.255] app list folder[0]: /usr/share/applications
[09:50:20.255] desktop file: /usr/share/applications/io.snapcraft.SessionAgent.desktop has NoDisplay specified
[09:50:20.255] app list entry failed to update: Key:SessionAgent
[09:50:20.255] free_app_entry(): (null): /usr/share/applications/io.snapcraft.SessionAgent.desktop
[09:50:20.256] Registered plugin API 'weston_xwayland_v1' of size 32
[09:50:20.256] Registered plugin API 'weston_xwayland_surface_v1' of size 48
[09:50:20.256] Not using abstract fd for Xwayland
[09:50:20.256] xserver listening on display :0
[09:50:20.256] Loading module '/usr/lib/weston/wslgd-notify.so'
[09:50:20.256] ../compositor/wslgd-notify.c: socket connected
[09:50:20.256] launching '/usr/libexec/weston-rdprail-shell'
[09:50:20.256] desktop file: /usr/share/applications/byobu.desktop is terminal based app
[09:50:20.256] app list entry failed to update: Key:byobu
[09:50:20.256] free_app_entry(): (null): /usr/share/applications/byobu.desktop
[09:50:20.257] desktop file: /usr/share/applications/python3.10.desktop has NoDisplay specified
[09:50:20.257] app list entry failed to update: Key:10
[09:50:20.257] free_app_entry(): (null): /usr/share/applications/python3.10.desktop
[09:50:20.258] desktop file: /usr/share/applications/htop.desktop is terminal based app
[09:50:20.258] app list entry failed to update: Key:htop
[09:50:20.258] free_app_entry(): (null): /usr/share/applications/htop.desktop
[09:50:20.258] desktop file: /usr/share/applications/snap-handle-link.desktop has NoDisplay specified
[09:50:20.258] app list entry failed to update: Key:snap-handle-link
[09:50:20.258] free_app_entry(): (null): /usr/share/applications/snap-handle-link.desktop
[09:50:20.258] desktop file: /usr/share/applications/info.desktop is terminal based app
[09:50:20.258] app list entry failed to update: Key:info
[09:50:20.258] free_app_entry(): (null): /usr/share/applications/info.desktop
[09:50:20.259] desktop file: /usr/share/applications/vim.desktop is terminal based app
[09:50:20.259] app list entry failed to update: Key:vim
[09:50:20.259] free_app_entry(): (null): /usr/share/applications/vim.desktop
[09:50:20.259] app list folder[1]: /usr/local/share/applications
[09:50:20.284] CreateWndow(): rdp_peer is not initalized
[09:50:20.320] Spawned Xwayland server, pid 23
[09:50:20.725] xf_peer_adjust_monitor_layout:
[09:50:20.725]   DesktopWidth:1920, DesktopHeight:1200
[09:50:20.725]   UseMultimon:0
[09:50:20.725]   ForceMultimon:0
[09:50:20.725]   MonitorCount:2
[09:50:20.725]   HasMonitorAttributes:1
[09:50:20.725]   HiDefRemoteApp:1
[09:50:20.725] disp_monitor_sanity_check_layout:---INPUT---
[09:50:20.725]  rdpMonitor[0]: x:0, y:0, width:1920, height:1200, is_primary:1
[09:50:20.725]  rdpMonitor[0]: physicalWidth:336, physicalHeight:210, orientation:0
[09:50:20.725]  rdpMonitor[0]: desktopScaleFactor:100, deviceScaleFactor:100
[09:50:20.725]  rdpMonitor[0]: scale:1, client scale :1.00
[09:50:20.725]  rdpMonitor[1]: x:1920, y:-95, width:3440, height:1440, is_primary:0
[09:50:20.725]  rdpMonitor[1]: physicalWidth:795, physicalHeight:334, orientation:0
[09:50:20.725]  rdpMonitor[1]: desktopScaleFactor:100, deviceScaleFactor:100
[09:50:20.725]  rdpMonitor[1]: scale:1, client scale :1.00
[09:50:20.850] Client: ClientStatus:0x3f5
[09:50:20.850]      - TS_RAIL_CLIENTSTATUS_ALLOWLOCALMOVESIZE
[09:50:20.850]      - TS_RAIL_CLIENTSTATUS_ZORDER_SYNC
[09:50:20.850]      - TS_RAIL_CLIENTSTATUS_WINDOW_RESIZE_MARGIN_SUPPORTED
[09:50:20.850]      - TS_RAIL_CLIENTSTATUS_HIGH_DPI_ICONS_SUPPORTED
[09:50:20.850]      - TS_RAIL_CLIENTSTATUS_APPBAR_REMOTING_SUPPORTED
[09:50:20.850]      - TS_RAIL_CLIENTSTATUS_POWER_DISPLAY_REQUEST_SUPPORTED
[09:50:20.850]      - TS_RAIL_CLIENTSTATUS_GET_APPID_RESPONSE_EX_SUPPORTED
[09:50:20.850]      - TS_RAIL_CLIENTSTATUS_BIDIRECTIONAL_CLOAK_SUPPORTED
[09:50:20.850] Client HandShake buildNumber:22000
[09:50:20.861] Server AppList caps version:3
[09:50:20.882] Client: gfxredir_caps: length:28
[09:50:20.882] Client: gfxredir_caps[0]: signature:0x53504143
[09:50:20.882] Client: gfxredir_caps[0]: version:0x1
[09:50:20.882] Client: gfxredir_caps[0]: length:12
[09:50:20.882] Client: gfxredir_caps[1]: signature:0x53504143
[09:50:20.882] Client: GrfxCaps count:0x9
[09:50:20.882] Client: GrfxCaps[0] version:0x80004 length:4 flags:0x0
[09:50:20.882]  Version : RDPGFX_CAPVERSION_8
[09:50:20.882] Client: GrfxCaps[1] version:0x80105 length:4 flags:0x0
[09:50:20.882]  Version : RDPGFX_CAPVERSION_81
[09:50:20.882] Client: gfxredir_caps[1]: version:0x2000
[09:50:20.882] Client: GrfxCaps[2] version:0xa0002 length:4 flags:0x0
[09:50:20.882] Client: gfxredir_caps[1]: length:16
[09:50:20.882]  Version : RDPGFX_CAPVERSION_10
[09:50:20.882] Client: gfxredir_caps[1]: supportedFeatures:0x0
[09:50:20.882] Client: gfxredir selected caps: version:0x2000
[09:50:20.882] Client: GrfxCaps[3] version:0xa0200 length:4 flags:0x0
[09:50:20.882]  Version : RDPGFX_CAPVERSION_102
[09:50:20.882] Client: GrfxCaps[4] version:0xa0301 length:4 flags:0x0
[09:50:20.882]  Version : RDPGFX_CAPVERSION_103
[09:50:20.882] Client: GrfxCaps[5] version:0xa0400 length:4 flags:0x0
[09:50:20.882]  Version : RDPGFX_CAPVERSION_104
[09:50:20.882] Client: GrfxCaps[6] version:0xa0502 length:4 flags:0x0
[09:50:20.882]  Version : RDPGFX_CAPVERSION_105
[09:50:20.882] Client: GrfxCaps[7] version:0xa0600 length:4 flags:0x0
[09:50:20.882]  Version : RDPGFX_CAPVERSION_106
[09:50:20.882] Client: GrfxCaps[8] version:0xb0101 length:4 flags:0x0
[09:50:20.882]  Version : UNKNOWN(721153)
[09:50:20.892] xf_peer_adjust_monitor_layout:
[09:50:20.892]   DesktopWidth:1920, DesktopHeight:1200
[09:50:20.892]   UseMultimon:0
[09:50:20.892]   ForceMultimon:0
[09:50:20.892]   MonitorCount:2
[09:50:20.892]   HasMonitorAttributes:1
[09:50:20.892]   HiDefRemoteApp:1
[09:50:20.892] disp_monitor_sanity_check_layout:---INPUT---
[09:50:20.892]  rdpMonitor[0]: x:0, y:0, width:1920, height:1200, is_primary:1
[09:50:20.892]  rdpMonitor[0]: physicalWidth:336, physicalHeight:210, orientation:0
[09:50:20.892]  rdpMonitor[0]: desktopScaleFactor:100, deviceScaleFactor:100
[09:50:20.892]  rdpMonitor[0]: scale:1, client scale :1.00
[09:50:20.892]  rdpMonitor[1]: x:1920, y:-95, width:3440, height:1440, is_primary:0
[09:50:20.892]  rdpMonitor[1]: physicalWidth:795, physicalHeight:334, orientation:0
[09:50:20.892]  rdpMonitor[1]: desktopScaleFactor:100, deviceScaleFactor:100
[09:50:20.892]  rdpMonitor[1]: scale:1, client scale :1.00
[09:50:20.892] kbd_layout:0x20409 kbd_type:0x4 kbd_subType:0x0 kbd_functionKeys:0xc
[09:50:20.892] convert_rdp_keyboard_to_xkb_rule_names: matching model=pc105 layout=us variant=intl options=(null)
[09:50:20.896] Head attaching: rdp-2, index:2, is_primary: 0
[09:50:20.896] Client desktop upper left coordinate (0,-95)
[09:50:20.896]  All monitors are horizontally placed
[09:50:20.896] disp_monitor_validate_and_compute_layout:---OUTPUT---
[09:50:20.896]  rdpMonitor[0]: x:0, y:0, width:1920, height:1200, is_primary:1
[09:50:20.896]  rdpMonitor[0]: weston x:0, y:95, width:1920, height:1200
[09:50:20.896]  rdpMonitor[0]: physicalWidth:336, physicalHeight:210, orientation:0
[09:50:20.896]  rdpMonitor[0]: desktopScaleFactor:0, deviceScaleFactor:100
[09:50:20.896]  rdpMonitor[0]: scale:1, clientScale:1.00
[09:50:20.896]  rdpMonitor[1]: x:1920, y:-95, width:3440, height:1440, is_primary:0
[09:50:20.896]  rdpMonitor[1]: weston x:1920, y:0, width:3440, height:1440
[09:50:20.896]  rdpMonitor[1]: physicalWidth:795, physicalHeight:334, orientation:0
[09:50:20.896]  rdpMonitor[1]: desktopScaleFactor:0, deviceScaleFactor:100
[09:50:20.896]  rdpMonitor[1]: scale:1, clientScale:1.00
[09:50:20.896] Head mode change:rdp-0 NEW width:1920, height:1200, scale:1, clientScale:1.000000
[09:50:20.896] move head/output rdp-0 (0,0) -> (0,95)
[09:50:20.896] Head mode change:rdp-2 NEW width:3440, height:1440, scale:1, clientScale:1.000000
[09:50:20.896] move head/output rdp-2 (0,0) -> (1920,0)
[09:50:20.896] client origin (0,0) is (0,95) in Weston space
[09:50:20.896] Output 'rdp-2' enabled with head(s) rdp-2
[09:50:20.896] Client ExecOrder:0x00000008, Program:dummy-entry, WorkingDir:(null), RemoteApplicationArguments:(null)
[09:50:20.896] Client ExecOrder launching dummy-entry
[09:50:20.896] launching 'dummy-entry'
[09:50:20.897] Client: ClientSysparam: filterKeys
[09:50:20.897] compositor: executing 'dummy-entry' failed: No such file or directory
[09:50:20.897] Client: ClientSysparam: toggleKeys:62
[09:50:20.897] Client: ClientSysparam: stickyKeys:510
[09:50:20.897] Client: ClientSysparam: caretWidth:1
[09:50:20.897] Client: ClientSysparam: highContrast
[09:50:20.897] Client: ClientSysparam: taskbarPos:(left:0, top:0, right:1920, bottom:40)
[09:50:20.897] Client: ClientSysparam: mouseButtonSwap:0
[09:50:20.897] Client: ClientSysparam: keyboardPref:0
[09:50:20.897] Client: ClientSysparam: dragFullWindows:1
[09:50:20.897] Client: ClientSysparam: keyboardCues:0
[09:50:20.897] Client: ClientSysparam: workArea:(left:1920, top:65481, right:5360, bottom:1345)
[09:50:20.897] Translated workarea:(1920,40)-(5360,1440) at rdp-2:(1920,0)-(5360,1440)
[09:50:20.897] Client: ClientSysparam: workArea:(left:0, top:40, right:1920, bottom:1200)
[09:50:20.897] Translated workarea:(0,135)-(1920,1295) at rdp-0:(0,95)-(1920,1295)
[09:50:20.897] Client AppList caps version:3
[09:50:20.897] Client AppList client language id: en_US
[09:50:20.897] app_list_monitor_thread: startRdpNotifyEvent is signalled. 0 - en_US
[09:50:20.897] Client ExecOrder program terminated
[09:50:20.897] dummy-entry exited with status 255
[09:50:20.898] xfixes version: 5.0
[09:50:20.903] created wm, root 912
[09:50:21.666] Pulse Audio Sink listener socket on /mnt/wslg/PulseAudioRDPSink
[09:50:21.668] Client: ClientSysparam: filterKeys
[09:50:21.668] Client: ClientSysparam: toggleKeys:62
[09:50:21.668] Client: ClientSysparam: stickyKeys:510
[09:50:21.668] Client: ClientSysparam: caretWidth:1
[09:50:21.668] Client: ClientSysparam: highContrast
[09:50:21.668] Client: ClientSysparam: taskbarPos:(left:0, top:0, right:1920, bottom:40)
[09:50:21.668] Client: ClientSysparam: mouseButtonSwap:0
[09:50:21.668] Client: ClientSysparam: keyboardPref:0
[09:50:21.668] Client: ClientSysparam: dragFullWindows:1
[09:50:21.668] Client: ClientSysparam: keyboardCues:0
[09:50:21.668] Client: ClientSysparam: workArea:(left:1920, top:65481, right:5360, bottom:1345)
[09:50:21.668] Translated workarea:(1920,40)-(5360,1440) at rdp-2:(1920,0)-(5360,1440)
[09:50:21.668] Client: ClientSysparam: workArea:(left:0, top:40, right:1920, bottom:1200)
[09:50:21.668] Translated workarea:(0,135)-(1920,1295) at rdp-0:(0,95)-(1920,1295)
[09:50:25.911] RDP Sink version (1 - 1)
[09:55:20.892] rdp_rail_idle_handler is called on peer_ctx:0x5636714cfda0
```

</details>

<details>
<summary>pulseaudio.log</summary>

```
W: [pulseaudio] authkey.c: Failed to open cookie file '/home/wslg/.config/pulse/cookie': No such file or directory
W: [pulseaudio] authkey.c: Failed to load authentication key '/home/wslg/.config/pulse/cookie': No such file or directory
W: [pulseaudio] authkey.c: Failed to open cookie file '/home/wslg/.pulse-cookie': No such file or directory
W: [pulseaudio] authkey.c: Failed to load authentication key '/home/wslg/.pulse-cookie': No such file or directory
E: [pulseaudio] module-console-kit.c: GetSessionsForUnixUser() call failed: org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.ConsoleKit was not provided by any .service files
E: [pulseaudio] module.c: Failed to load module "module-console-kit" (argument: ""): initialization failed.
E: [rdp-sink] module-rdp-sink.c: RDP Sink - Trying to connect to /mnt/wslg/PulseAudioRDPSink
E: [rdp-sink] module-rdp-sink.c: Connected failed
E: [rdp-sink] module-rdp-sink.c: RDP Sink - Trying to connect to /mnt/wslg/PulseAudioRDPSink
E: [rdp-sink] module-rdp-sink.c: RDP Sink - Connected to fd 12
```

</details>

### WSL dumps:

Dir `/mnt/wslg/dumps` is empty

### Expected behavior:

An x11 window opens

### Actual behavior:

No x11 window opens but the application works fine according to the stdout.

```
❯ echo $DISPLAY
172.17.128.1:0.0
```

Setting `$DISPLAY` `:0` does not work:
![image](https://user-images.githubusercontent.com/111898561/194821941-d26ceb7c-7b0c-4e96-99fc-ef65eb2ff3dc.png)

No x11 server seems to be running though:
```
❯ ls /tmp/.X11-unix
```

Recreating the link also does not change the behaviour:
```
❯ ln -s /mnt/wslg/.X11-unix /tmp/.X11-unix
ln: replace '/tmp/.X11-unix/.X11-unix'? y
'/tmp/.X11-unix/.X11-unix' -> '/mnt/wslg/.X11-unix'
~ [  (eu-central-1)]⏱ 6s
❯ ls /tmp/.X11-unix
~ [  (eu-central-1)]
❯ xeyes
```

**Comment by hideyukn88** [comment]
Please update to WSL 0.70.0 by `wsl --update`, and check if this is still issue, we have addressed several X connection issues in this release, thanks!

**Comment by lohrm-stabl** [comment]
@hideyukn88 I updated my WSL to 0.70.0 and the issue persists:

```
PS C:\Users\MichaelLohr> wsl.exe --version
WSL version: 0.70.0.0
Kernel version: 5.15.68.1
WSLg version: 1.0.45
MSRDC version: 1.2.3575
Direct3D version: 1.606.4
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.22000.1098
```

Please reopen this issue

**Comment by hideyukn88** [comment]
@lohrm-stabl, @virtuluv, thanks for checking with the latest WSL, I reopened the issue, thanks!

**Comment by crramirez** [comment]
> you should try this. my X-11 apps don't work too but I found this one. or may be just uninstall Xming and install VcXsrv Windows X Server instead. https://stackoverflow.com/questions/43397162/show-matplotlib-plots-and-other-gui-in-ubuntu-wsl1-wsl2

Hello @Koonarm,

These instructions are related to using GUI without WSLg, which is different from using WSLg.

For WSLg and Windows 11, the DISPLAY variable should be DISPLAY=:0
For external X11 and Windows 10 variable should be DISPLAY=#.#.#.#:0 where #.#.#.# is the IP in /etc/resolv.conf to your host IP. For this, you'll also need an X server like VcXSrv or Xming, X410, etc.

The issue as described is related to WSLg

Regards,
Carlos

**Comment by lohrm-stabl** [comment]
> For WSLg and Windows 11, the DISPLAY variable should be DISPLAY=:0 For external X11 and Windows 10 variable should be DISPLAY=#.#.#.#:0 where #.#.#.# is the IP in /etc/resolv.conf to your host IP. For this, you'll also need an X server like VcXSrv or Xming, X410, etc.

This is quite interesting. Since mine is set to the host IP (I think, at least it's not 0). But it seems to respond to the app, since it does not throw any connection error, but actually connects to something and runs (but without opening any window).

![image](https://user-images.githubusercontent.com/111898561/196410072-8eea6fbc-597a-4c7f-8069-cad9e44ebbd9.png)

As I just wanted to send you an image of what happens when forcing the display variable to 0 (which did not work before), it just worked....

![image](https://user-images.githubusercontent.com/111898561/196410808-ae553d8d-3194-41e5-bfb9-d69a8aefe082.png)

So it seems to have fixed itself somehow. I tried it nearly everyday the last week and it didn't work, so that is very weird.

**Comment by hideyukn88** [comment]
@gmsh, if you manually recreate the link following https://github.com/microsoft/wslg/wiki/Diagnosing-%22cannot-open-display%22-type-issues-with-WSLg, does it solve? thanks!

**Comment by gmsh** [comment]
@hideyukn88 Thanks for asking.

I did the following steps but it still doesn't work.

```zsh
➜  ~ sudo rm -r /tmp/.X11-unix
rm: cannot remove '/tmp/.X11-unix': Device or resource busy
➜  ~ mount
none on /mnt/wsl type tmpfs (rw,relatime)
drivers on /usr/lib/wsl/drivers type 9p (ro,nosuid,nodev,noatime,dirsync,aname=drivers;fmask=222;dmask=222,mmap,access=client,msize=65536,trans=fd,rfd=7,wfd=7)
none on /usr/lib/wsl/lib type overlay (rw,relatime,lowerdir=/gpu_lib_packaged:/gpu_lib_inbox,upperdir=/gpu_lib/rw/upper,workdir=/gpu_lib/rw/work)
/dev/sdc on / type ext4 (rw,relatime,discard,errors=remount-ro,data=ordered)
none on /mnt/wslg type tmpfs (rw,relatime)
/dev/sdc on /mnt/wslg/distro type ext4 (ro,relatime,discard,errors=remount-ro,data=ordered)
rootfs on /init type rootfs (rw,size=16351428k,nr_inodes=4087857)
none on /dev type devtmpfs (rw,nosuid,relatime,size=16351456k,nr_inodes=4087864,mode=755)
sysfs on /sys type sysfs (rw,nosuid,nodev,noexec,noatime)
proc on /proc type proc (rw,nosuid,nodev,noexec,noatime)
devpts on /dev/pts type devpts (rw,nosuid,noexec,noatime,gid=5,mode=620,ptmxmode=000)
none on /run type tmpfs (rw,nosuid,nodev,mode=755)
none on /run/lock type tmpfs (rw,nosuid,nodev,noexec,noatime)
none on /run/shm type tmpfs (rw,nosuid,nodev,noatime)
none on /run/user type tmpfs (rw,nosuid,nodev,noexec,noatime,mode=755)
binfmt_misc on /proc/sys/fs/binfmt_misc type binfmt_misc (rw,relatime)
tmpfs on /sys/fs/cgroup type tmpfs (rw,nosuid,nodev,noexec,relatime,mode=755)
cgroup2 on /sys/fs/cgroup/unified type cgroup2 (rw,nosuid,nodev,noexec,relatime,nsdelegate)
cgroup on /sys/fs/cgroup/cpuset type cgroup (rw,nosuid,nodev,noexec,relatime,cpuset)
cgroup on /sys/fs/cgroup/cpu type cgroup (rw,nosuid,nodev,noexec,relatime,cpu)
cgroup on /sys/fs/cgroup/cpuacct type cgroup (rw,nosuid,nodev,noexec,relatime,cpuacct)
cgroup on /sys/fs/cgroup/blkio type cgroup (rw,nosuid,nodev,noexec,relatime,blkio)
cgroup on /sys/fs/cgroup/memory type cgroup (rw,nosuid,nodev,noexec,relatime,memory)
cgroup on /sys/fs/cgroup/devices type cgroup (rw,nosuid,nodev,noexec,relatime,devices)
cgroup on /sys/fs/cgroup/freezer type cgroup (rw,nosuid,nodev,noexec,relatime,freezer)
cgroup on /sys/fs/cgroup/net_cls type cgroup (rw,nosuid,nodev,noexec,relatime,net_cls)
cgroup on /sys/fs/cgroup/perf_event type cgroup (rw,nosuid,nodev,noexec,relatime,perf_event)
cgroup on /sys/fs/cgroup/net_prio type cgroup (rw,nosuid,nodev,noexec,relatime,net_prio)
cgroup on /sys/fs/cgroup/hugetlb type cgroup (rw,nosuid,nodev,noexec,relatime,hugetlb)
cgroup on /sys/fs/cgroup/pids type cgroup (rw,nosuid,nodev,noexec,relatime,pids)cgroup on /sys/fs/cgroup/rdma type cgroup (rw,nosuid,nodev,noexec,relatime,rdma)cgroup on /sys/fs/cgroup/misc type cgroup (rw,nosuid,nodev,noexec,relatime,misc)none on /mnt/wslg/versions.txt type overlay (rw,relatime,lowerdir=/systemvhd,upperdir=/system/rw/upper,workdir=/system/rw/work)
none on /mnt/wslg/doc type overlay (rw,relatime,lowerdir=/systemvhd,upperdir=/system/rw/upper,workdir=/system/rw/work)
tmpfs on /var/tmp type tmpfs (rw,relatime)
none on /tmp/.X11-unix type tmpfs (rw,relatime)
drvfs on /mnt/c type 9p (rw,noatime,dirsync,aname=drvfs;path=C:\;uid=1000;gid=1000;symlinkroot=/mnt/,mmap,access=client,msize=262144,trans=virtio)
➜  ~ sudo umount /tmp/.X11-unix
➜  ~ sudo rm -r /tmp/.X11-unix
➜  ~ sudo ln -s /mnt/wslg/.X11-unix /tmp/.X11-unix
➜  ~ cat /mnt/wslg/versions.txt
WSLg ( x86_64 ): 1.0.45+Branch.main.Sha.254cbbc0eb26fe4bf82e9656470ebb5546a84a23Mariner: VERSION="2.0.20220426"
DirectX-Headers:
mesa:
pulseaudio: 2f0f0b8c3872780f15e275fc12899f4564f01bd5
FreeRDP: c574044a10003e50453acb4cf42801c5833fb572
weston: 2270ceb3cf75a03e8b3f073eca2c5dc04b12e504
➜  ~ echo $DISPLAY
:0
➜  ~ ls -la /tmp/.X11-unix
lrwxrwxrwx 1 root root 19 Oct 19 16:30 /tmp/.X11-unix -> /mnt/wslg/.X11-unix
➜  ~ ls -la /tmp/.X11-unix/
total 0
drwxrwxrwx 2 root root  40 Oct 19 16:20 .
drwxrwxrwt 7 root root 280 Oct 19 16:20 ..
➜  ~ xeyes
Error: Can't open display: :0
```
And here is the weston.log . Thanks!
[weston.log](https://github.com/microsoft/wslg/files/9824970/weston.log)

**Comment by hideyukn88** [comment]
@gmsh, the socket is no longer symlink between /tmp and /mnt/wslg, so manually restore them won't work. Can you do below to write something on /mnt/wslg/.X11-unix, and see if file "foo" is visible from /tmp/.X11-unix as well? this ensure they are mounted at same point, thanks!

```
 echo foo > /mnt/wslg/.X11-unix/foo
 cat /tmp/.X11-unix/foo
 foo
```

**Comment by gmsh** [comment]
@hideyukn88 Thanks for the prompt response. 
Yep, they are.
```zsh
➜  ~ echo foo > /mnt/wslg/.X11-unix/foo
➜  ~ cat /tmp/.X11-unix/foo
foo
```

```cmd
c:\Windows\System32>wsl -l -v
  NAME                   STATE           VERSION
* Ubuntu-22.04           Stopped         2
  Ubuntu                 Stopped         2
  openSUSE-Tumbleweed    Running         2

c:\Windows\System32>wsl --system -d openSUSE-Tumbleweed -u root cat /mnt/wslg/.X11-unix/foo
foo

c:\Windows\System32>wsl --system -d openSUSE-Tumbleweed -u root cat /tmp/.X11-unix/foo
foo
```

**Comment by hideyukn88** [comment]
@gmsh, by looking at weston.log from https://github.com/microsoft/wslg/issues/853#issuecomment-1284700850, I noticed below, do you see any core dumps at /mnt/wslg/dumps? thanks!

>> [16:20:51.445] xserver crashing too fast: 134

**Comment by gmsh** [comment]
@hideyukn88 thanks for the investigation. Here it is. 
[dump.zip.zip](https://github.com/microsoft/wslg/files/9825349/dump.zip.zip)

**Comment by hideyukn88** [comment]
@gmsh, it looks there is some exception from GPU acceleration modules, would you please disable Display Drivers at Windows's Device Manager (below) and `wsl --shutdown`, then please try again, thanks!

<img width="213" alt="image" src="https://user-images.githubusercontent.com/13857962/196849113-6fa7342d-31b4-4532-a95a-5f9ffdb8aeb6.png">

**Comment by gmsh** [comment]
@hideyukn88 Thanks! It worked after disabling the Display Drivers. But I am afraid I could not disable it for everyday usage.
![image](https://user-images.githubusercontent.com/396089/196849970-183faa81-4cc6-4da5-9a39-aedf90b35cad.png)

And here is the driver's information.
![image](https://user-images.githubusercontent.com/396089/196850159-a151279e-ba84-4571-a718-d28efbe2db47.png)

**Comment by hideyukn88** [comment]
@gmsh, thanks for confirming it, if you don't mind, would you please install a bit older version of Intel driver, version 30.0.101.1660, from https://www.intel.com/content/www/us/en/download/19344/727284/intel-graphics-windows-dch-drivers.html, and see it works? thanks!

**Comment by gmsh** [comment]
@hideyukn88 Thanks for the detailed instructions. However, it doesn't work with the `30.0.101.1660` driver, either.
![image](https://user-images.githubusercontent.com/396089/196858854-094cc9eb-a35d-4473-8518-80a6ab8fe9f3.png)
Here is the new dump: [dump_30.0.101.1660.zip](https://github.com/microsoft/wslg/files/9826372/dump_30.0.101.1660.zip)

Please let me know if you need anything else.

**Comment by crramirez** [comment]
To help a bit, I have the same behavior, In my case, it happens frequently but not always and my driver is NVidia and I don't have an integrated graphics card. I'll follow this troubleshooting so I can help.

**Comment by hideyukn88** [comment]
@crramirez, would you please share core.Xwayland from /mnt/wslg/dump? thanks!

**Comment by hideyukn88** [comment]
@gmsh, what is your CPU model ? thanks!

**Comment by hideyukn88** [comment]
@gmsh, going forward the issue with those Pentium Silver N6000 series issue will be tracked by https://github.com/microsoft/wslg/issues/877.

 And base on above https://github.com/microsoft/wslg/issues/853#issuecomment-1282198923, I believe the original issue is now solved, so I will close this issue.
